app/js/plex/PlexTv.js
Because it will not work with these IPs.
=> Exclude local IPs starting with 169.254

app/app.js, app/js/settings.js, app/package.json, app/ptsettings.html
Will need to run npm nstall to install missing package
=> Save custom pt server

server.js, src/sidebar.vue, src/store.js
Allows the host to appoint a new host by double-clicking on another user's avatar. Useful for giving control to another user.
=> Allow the host to transfer hosting to another user

webapp.js
After running into some issues when setting up the server through a reverse proxy, I noticed some inconsistencies with the webroot setting not being used for the webapp. This PR should fix those issues as well as clean-up some of the webapp code.
- Fix webroot issues
- Clean-up accessIp/accessUrl
- Remove duplicate CORS
- Remove duplicate static mapping
- Update comments and some outputs
=> Update webapp with fixes and changes

src/App.vue
- Fix a console error for `gotDevices` that doesn't seem to break anything but just bothers me =)
- Settings store variables for autoJoin weren't getting set before going to the sign-in screen. Made these be set in what I think is the order of importance: query -> config -> settings
Should be the final fix to close issue https://github.com/samcm/synclounge/issues/125
=> Should fix autoJoin on login

SettingsHelper.js, src/App.vue, src/components/signin.vue, src/store.js, src/store/modules/plex/actions.js
- Include new fields
- Group by web/server
- Provide some additional output
=> Update to SettingsHelper

server.js
Fix for https://github.com/samcm/synclounge/issues/160
=> Fix server port variable

src/components/signin.vue
=> Revert "Add a dialog to disable popup blocking"

SettingsHelper.js
Add logic to parse some of the settings that are expected to be a JSON object or an Array of JSON objects
=> Add logic to parse some of the settings

server.js
- Show 'Total Connected users' on connect and disconnect
- Move base URL (serverroot) information to output after server start
- Remove interval to show connected users
=> Update server output

src/store/modules/plex/helpers/PlexClient.js
Adds a fix for the URL library where the port isn't stored if the port is standard for the protocol.
=> Fix port/protocol for the node URL library.

src/components/signin.vue
- Activate spinner during checkAuth
- Get user devices instead of servers
- Change object handling
- Fix server ID check
=> Fix auth by server

webapp.js
- Add accessUrl warning if it doesn't contain webroot
- Output Authentication setting, if set
- Output Servers setting, if set, otherwise, output Custom Server, if set
=> Update webapp output

src/components/application/walkthrough.vue, src/store/modules/plex/actions.js
- Add information for Android and Windows clients
- Filter Plex Web clients from the client list
=> Plex client filtering and information

server.js
This allows XHR requests across origins since previous restrictive policies were causing issues such as #143
=> More permissive CORS policies

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/stale.yml
- Add default labels to new reports
- Update stale workflow to respect these labels, as appropriate.
=> Stale bot updates

src/store/modules/slplayer/actions.js
Fix lint issue detected by new eslint.
Fixes failing tests on https://github.com/synclounge/synclounge/pull/234
=> style: fix lint issue

.github/workflows/ci.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.web, package-lock.json, package.json, src/App.vue, src/components/TheSidebarLeft.vue, src/store/getters.js, src/store/modules/plex/getters.js, src/store/state.js, src/views/SignIn.vue, vue.config.js
Remove things like build date and sha from app to improve build repeatability and caching. The version should take care of both of those needs instead.
Also moves labels into actions from the dockerfiles.
=> refactor(docker): make builds more repeatable

config/defaults.js, src/store/modules/synclounge/actions.js, src/store/modules/synclounge/getters.js, src/store/modules/synclounge/state.js
=> feat(notifications): add config for setting notification defaults

.github/workflows/release.yml
This will fix the reported action release failures
=> ci(release): use new dockerhub-description format

src/main.js, src/store/modules/plex/actions.js, src/store/modules/plex/getters.js, src/views/AdvancedRoomWalkthrough.vue, src/views/SignIn.vue
Closes: https://github.com/synclounge/synclounge/issues/316
=> fix(autojoin): redirect after signin

src/views/AdvancedRoomJoin.vue
Closes: https://github.com/synclounge/synclounge/issues/327
=> fix(join): fix custom server input

package-lock.json, package.json
Refs: https://github.com/vuetifyjs/vuetify/issues/12586
Closes: https://github.com/synclounge/synclounge/issues/362
=> fix(search): downgrade to Vuetify v2.3.16

package-lock.json, package.json
The parameter encoding is now fixed as of: https://github.com/vuejs/vue-router/pull/3350
=> build(dev-deps): update vue-router to 3.4.9

README.md
Adds some more detail on how to pass json configurations as env vars in docker
=> add example json env configuration

.gitattributes, src/player/index.js, src/store/modules/slplayer/getters.js
This pull request fixes #824 the subtitle and audio selection for the latest plex versions.
=> Fix subtitle and audio selection

README.md
Corrected typo error for "flexibility"
=> README.md - fix
