src/components/application/ptplayer.vue, src/components/application/ptplayer/videoplayer.vue
Even when the "Resume from [some time offset]" checkbox was checked, videos were starting from the beginning. Now they resume from the offset.
=> Fix "Resume from" functionality for PT player

src/assets/js/plex/PlexServer.js, src/components/application/plexbrowser.vue, src/components/application/plexbrowser/plexcontent.vue, src/components/application/plexbrowser/plexserver.vue
Any feedback would be welcome, I'm not familiar with the framework and codebase.
The first commit keeps the on-deck information up-to-date when browsing around, which is useful because items can easily be added or removed from it when something is watched or marked (un)watched on another player.
The second commit adds a "Mark Unwatched" button, that I find very helpful for videos that have been partially watched that I don't intend to finish, to easily remove them from the deck. The first commit ensures that videos that have just been marked as watched disappear from the deck when returning to it.
=> Add "mark unwatched" button

webapp.js
Seems like encoded server URLs result in an invalid Invite URL. By making this change, I was able to generate valid Invite URLs, even when the room had special characters in the password/room name. I am not sure what the original intent of this code was, or if I am missing something. I did test it in my scenario, and it worked.
=> Don't run encodeURIComponent on Invite parameters

src/components/application/plexbrowser.vue
The 10em height attribute was forcing the container height for the
server browsing components to be 10em. This meant that in the case of long server
names, the text would grow outside of the container. By removing the
10em height attribute, we can flexibly grow/shrink the container to the 
text height.
**Before:**
**After:**
=> Allow flexable height for server browser container

server.js, src/sidebar.vue, src/store/modules/synclounge.js
Closes #110 
Changes the "PAUSE" button to allow others in the room to play or pause depending on the host's current state when Party Pausing is enabled.
Hides the button entirely when the host is in the "stopped" state.
Demo: https://v.eryn.io/njh2chtmq6.mp4
=> Add Play ability to Party Pausing

package-lock.json, package.json, src/App.vue, src/assets/css/style.css, src/components/application/plexbrowser.vue, src/components/application/plexbrowser/plexcontent.vue, src/components/application/plexbrowser/plexseason.vue, src/components/application/plexbrowser/plexseries.vue, src/components/application/plexbrowser/plexthumb.vue, src/components/application/ptplayer.vue, src/components/application/ptplayer/videoplayer.vue, src/components/message.vue, src/components/messages.vue, src/sidebar.vue, src/upnext.vue
Summary:
- Hide toolbar when fullscreen
- Split messages into separate, reusable components
- Move messages to below video on mobile
- Size player to 16x9 on mobile
- Disable send button if no message
- Add icon to send button
- Switch message field to single-line for compactness
Notes:
I tested this on my Pixel 2 XL. Messages on mobile works best when in fullscreen, allowing for a comparable experience to rabb.it's mobile app.
=> Improve messages on mobile

src/components/application/plexbrowser/plexserver.vue
Since music syncing isn't supported, this will filter them from the list and stop questions coming in about why syncing music won't work until it is fully supported.
Revert this filtering when issue https://github.com/samcm/synclounge/issues/47 is completed.
=> Filter music libraries from list

SettingsHelper.js, example_settings.json, src/App.vue, src/components/application/joinroom.vue
Updates servers handling to:
- Allow users to override the custom server entry (`customServer` setting) in the default list.
Example setting:
```json
"customServer": {
"name": "Custom Server 1",
"location": "Custom Location",
"url": "https://mycustomserver.com/server",
"logo": "https://mycustomserver.com/logo.png"
}
```
Result:
- Allow users to set their own servers (`servers` setting)
The servers list can also handle a default Room with or without password. If set, it will attempt to auto-join the room when the server is selected.
Example setting:
```json
"servers": [
{
"name": "Custom Server 1",
"location": "Custom Location",
"url": "https://1.mycustomserver.com/server",
"logo": "https://mycustomserver.com/logo.png"
},
{
"name": "Custom Server 2",
"location": "Custom Location",
"url": …
```
=> User defined servers list and custom server override

SettingsHelper.js, src/App.vue, src/components/signin.vue, src/store.js, src/store/modules/plex/actions.js
This provides an authentication mechanism for users that set up their own SyncLounge.
To set this, the following setting and format is used
```json
"authentication": {
"mechanism": "plex",
"type": ["server", "user"],
"authorized": [
"PLEX_SERVER_MACHINE_ID",
"PLEX_USER_EMAIL",
"PLEX_USER_NAME",
]
}
```
- `mechanism` specifies how SyncLounge should authenticate a user. This is mostly for future-proofing to allow other authentication mechanisms to be provided. Defaults to `none`.
- `type` is mechanism dependent. Since `plex` is the only one currently, either or both `server` and `user` can be specified.
- `server` checks against the plex server machine ID (`PLEX_SERVER_MACHINE_ID`). If the user has access to a server matching any of the IDs in the `authorized` list, they will be granted …
=> Authentication

src/leftsidebar.vue
Partially in preparation for something else I'm working on, I've done the following to the left sidebar:
- Synclounge vX.X.X now links to the website
- Added a link to SyncLounge Discord
- Added a link to SyncLounge GitHub
- Added Donate link and modal
There is a better way to do the Donate modal that doesn't require it being imported with leftsidebar.vue, but that'll be a later endeavor.
=> Add links to left sidebar

src/components/signin.vue
Fix for issue https://github.com/samcm/synclounge/issues/155
If SyncLounge fails to open the popup or new window, it will display a popup dialog (that could probably use a bit of styling fitness, but it works!).
=> Add a dialog to disable popup blocking

package-lock.json, package.json, src/components/signin.vue, src/main.js
Update for https://github.com/samcm/synclounge/issues/168 and https://github.com/causefx/Organizr/issues/1344. 
Changes:
- Added vue-cookies library
- Added the import and things to main.js
- Added the check for the cookie to sign-in.vue
=> Update OAuth to work on different sub-domains

src/sidebar.vue
- Add colon before room name
- Add a banner at the top of the sidebar for guests
- Add menu for each guest for actions
- Add "Make Host" action
- Offset menu options to prevent accidental clicks on menu items
=> sidebar updates

src/App.vue
A random edge case that was discovered by accident. A user is able to go to the `/joinroom` route without being authenticated via Plex. Not a huge issue since nothing can be done from there but just in case.
=> Always force signin if the user hasn't authenticated with Plex

.github/workflows/stale.yml
This will run at midnight (GitHub server time) to mark Issues or PRs as stale after 60 days of no activity and close them 7 days after that.
Issues/PRs can be ignored by this by adding the label `keep-open` to them if needed.
=> Add workflow to mark issues/PRs stale then close

SettingsHelper.js
This solves the issue mentioned in https://github.com/Starbix/docker-synclounge/issues/13#issue-601644724
```
ErrorWarningSystemArrayLogin
sh: : unknown operand
Rebuilding Webapp for custom options support. This can take a minute or two.
npm WARN SyncLounge@2.0.0 No repository field.
npm WARN SyncLounge@2.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
audited 11620 packages in 8.946s
found 623 vulnerabilities (159 low, 17 moderate, 447 high)
run `npm audit fix` to fix them, or `npm audit` for details
> SyncLounge@2.0.0 build /opt/synclounge
> node build/build.js …
```
=> Stringify authentication's default value

src/components/application/ptplayer.vue, src/components/application/ptplayer/videoplayer.vue
The web player will now keep its place when changing qualities, audio tracks, and subtitles. 
The web player will also now not always load the first segment when resuming/starting from the middle of a video.
=> Keep spot when changing quality

src/store/modules/synclounge.js
Autoplay if rawTitle sent from host doesn't match the rawTitle the host sent last time an autoplay was done. This fixes an issue where clients weren't properly switching to the next episode when the host let the next episode play with the "upnext" autoplay.
=> Autoplay if rawTitle doesn't match

src/components/application/ptplayer/videoplayer.vue
Current behavior is that volume is set to 0% when initially loading the app. This appears to have been done to give the player the best chance at autoplaying, however, the caution is unneeded. videojs describes [some suggestions](https://blog.videojs.com/autoplay-best-practices-with-video-js/) in dealing with autoplay and also links to policies of the major browsers.
In chrome, if the user has interacted with the domain (clicked) then autoplay with sound is enabled. Since a user always has to login to the app with Plex, this criteria is always met for chrome, along with selecting the player.
Additionally, the previous behavior of just setting the volume to 0 isn't enough and should have actually set the mute attribute instead to make it have the best chance. 
Finally, if autoplay does …
=> Default web play volume 100%

Dockerfile, Dockerfile.web
Dependabot missed the build stages so this bumps them manually
=> build(docker): bump node to v14.13.1

.github/workflows/release.yml
Wait to run checkout until previous releases finish in order to have the latest tags in the checked out repo. This is important because semantic release determines the next version based on the tags in the current repo.
=> ci(release): wait to checkout until previous release done

src/router/index.js
Add a default route that redirects to RoomCreation. Any urls that don't match any of the other routes will hit this. Without this, going to a non existent url will just show an empty router-view which isn't helpful.
=> refactor(router): add default route

Dockerfile, server.js
Use tini for init rather than manually writing signal handlers
=> build(docker): use tini for init

config/defaults.js, src/store/index.js, src/store/modules/synclounge/actions.js, src/store/modules/synclounge/getters.js, src/store/modules/synclounge/mutations.js, src/store/modules/synclounge/state.js, src/views/AdvancedRoomJoin.vue
With the removal of room id visibility, having the recent room list around may cause confusion since it's the one place that room id is made visible.
=> refactor(join): remove recent rooms

src/main.js
Tested with both autojoin server specified and unspecified/empty string
=> fix(autojoin): use store instead of this

package-lock.json, package.json
Refs: c1fbd9f
Forgot to block dependabot from updating any future vue-router releases until https://github.com/vuejs/vue-router/issues/3337 is fixed. Looks like it may happen soon because there is an outstanding PR for it: https://github.com/vuejs/vue-router/pull/3350
I have now made dependabot ignore vue-router until I manually update it after that bug is fixed: https://github.com/synclounge/synclounge/pull/313#issuecomment-717428340
=> revert(router): use vue-router 3.4.5

src/components/TheSettingsDialog.vue, src/store/index.js, src/store/modules/slplayer/getters.js, src/store/modules/slplayer/mutations.js, src/store/modules/slplayer/state.js, src/views/WebPlayer.vue
The setting can be found in the settings dialog which can be opened from
the left sidebar.
Closes https://github.com/synclounge/synclounge/issues/246
=> feat(subtitles): add force burn subtitles setting
